greeting.message: "<h1 align='center'>Hello, Welcome to Spring Boot World</h1>"
mylist: "one,two,three"
dbValues: "{url:'htt://localhost---', userName:'abcd123', password:'pwd123'}"

db:
  connectionUrl: com.jdbc.mysql
  host: localhost
  port: 3306

management.endpoints.web.exposure.include: "*"


spring:
  application:
    name: My App
  profiles:
    active: test